### ISSUE TITLE
monitor_metrics.sh is reading the same lines in the p4log and errors.csv on every execution

### ISSUE THREAD

**Issue by jakeRM** [perforce/p4prometheus#11]
The way the monitoring script is pulling data that relies on logs seems to have a flaw. It is reading the entire log file ever time it is executed.

This is true for monitor_completed_cmds and monitor_errors functions.

I will be submitting a pull request to fix these problems and others.
To specifically address this problem I used a simple data file to record the last timestamps and line counts from the log files to determine where the last run had left off. It's not perfect but it's a good start

**Comment by rcowham** [comment]
One aspect of metrics is that rate of change is as important as thee absolute values.

**Comment by jakeRM** [comment]
I don't disagree, but rate of change can be calculated by comparing the collections themselves, in my humble opinion those collections should not include duplicate data points.
