### ISSUE TITLE
Log tailing stops working after an hour

### ISSUE THREAD

**Issue by seanhoughton** [perforce/p4prometheus#20]
I'm having problems on some servers with the log tailing seeming to stop with no obvious error messages in the log. In this case I restarted the p4prometheus service at 1:34 and it worked until 2:01 at which point all metrics went to zero. The prometheus textfile is being written, but none of the values are changing. Restarting the service gets it working again for a while and then it stops. Some servers which are running the same Ubuntu release and provisioned the same way with Puppet have been working well for days.

I can't seem to correlate this with journal rotations so I don't think it's related to a new log file showing up.

Note that I had this problem with the elastic beat exporter as well, so it's likely a problem with either the go-p4log module or the underlying tailing module. 

```
ug 04 01:34:21 ct-host-u38 p4prometheus[10996]: time="2021-08-04T01:34:21Z" level=info msg="watching new file" directory=/p4/1/logs fd=3 file=log
Aug 04 01:34:25 ct-host-u38 p4prometheus[10996]: time="2021-08-04T01:34:25Z" level=info msg="Resetting running to 923 as encountered server threads message"
Aug 04 02:24:06 ct-host-u38 p4prometheus[10996]: time="2021-08-04T02:24:06Z" level=info msg="watching new file" fd=7 file=log
Aug 04 02:24:06 ct-host-u38 p4prometheus[10996]: time="2021-08-04T02:24:06Z" level=info msg="file was removed, closing and un-watching" fd=3 file=log
Aug 04 06:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T06:00:02Z" level=info msg="watching new file" fd=3 file=log
Aug 04 06:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T06:00:02Z" level=info msg="file was removed, closing and un-watching" fd=7 file=log
Aug 04 07:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T07:00:02Z" level=info msg="watching new file" fd=7 file=log
Aug 04 07:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T07:00:02Z" level=info msg="file was removed, closing and un-watching" fd=3 file=log
Aug 04 15:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T15:00:02Z" level=info msg="watching new file" fd=3 file=log
Aug 04 15:00:02 ct-host-u38 p4prometheus[10996]: time="2021-08-04T15:00:02Z" level=info msg="file was removed, closing and un-watching" fd=7 file=log
```

**Comment by rcowham** [comment]
What version of Ubuntu?
What version of p4d, and what configurables are set (e.g. server/track/rpl)?
If it occurs again, might be worth checking if there is a bug in log file parsing as well - which can be done with the similar p4dlog.
How often do you rotate log files? Is it hourly?
