### ISSUE TITLE
Massive CPU usage

### ISSUE THREAD

**Issue by samhocevar** [perforce/p4prometheus#22]
p4prometheus uses a lot of memory (9 GiB), with no apparent reason:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/245089/146208806-1a852558-bd11-4b75-8fa8-0f48a0d34d92.png">

Is there a way to check what it’s actually doing?

**Comment by samhocevar** [comment]
Here is a chart of memory usage since the daemon was launched 10 days ago:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/245089/146212983-a91c3e81-5040-4221-bfb6-08566140ae15.png">

**Comment by hueyvle** [comment]
you can get the pid and do 
strace -p <pid>

**Comment by rcowham** [comment]
@samhocevar 
Which version of p4prometheus?
Which version of p4d are you using?
It uses the underlying library which is also used by log2sql: https://github.com/rcowham/go-libp4dlog/releases
What is the output of 'p4 configure show server'? Also 'p4 configure show track'?
It is possible there is some sort of error matching up start and end records.
2 options:

- Download log2sql and run it against your recent log file. 
- We can create a support case and you can upload via ftp your (zipped) log file and I can have a look.

**Comment by rcowham** [comment]
Closing due to lack of response.
