### ISSUE TITLE
Avoid creation of cruff temp files /p4/metrics if commands fail.

### ISSUE THREAD

**Issue by cttyler** [perforce/p4prometheus#30]
A common workflow in several scripts is to generate data to a temp file first, and move that data to the correct target file name on successful completion, so that only completed metrics data files appear for scraping by the node_exporter.

This enhancement is to better handle the case where commands fail. In that case, the temp files should be deleted.

Perhaps we consider doing something separate to indicate count of failures or some such?

**Comment by rcowham** [comment]
Fixed in 31dcbf7b8c13cec50e9208b029fdb923d8d966db
