### ISSUE TITLE
monitor_metrics.sh causes pull errors when run on non-replica servers

### ISSUE THREAD

**Issue by jakeRM** [perforce/p4prometheus#9]
The script does not currently detect if the server is a replica or not, so when the monitor_pull function is executed on a server other then a replica, the error of "Pull only allowed on replica servers."

A simple fix would be to encapsulate the same detection mechanism in the monitor_pull function that's used in the SDP scripts. 
```
monitor_pull () {
    if [[ "${P4REPLICA}" == "TRUE" ]]
        ....existing code
    fi
}
```

This won't work for non-SDP servers though unless they source a similar vars script.

**Comment by rcowham** [comment]
Yes - this was done to support non-SDP servers. Not considered terribly harmful for SDP ones. But maybe some more intelligence possible for SDP ones...

**Comment by rcowham** [comment]
Fixed
